CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE COLLATE NOCASE, passwordHash TEXT, role TEXT NOT NULL CHECK(role IN ('admin','pm')), active INTEGER NOT NULL DEFAULT 1, createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (tokenHash TEXT PRIMARY KEY, userId TEXT NOT NULL REFERENCES users(id), expiresAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tokens (tokenHash TEXT PRIMARY KEY, userId TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL, expiresAt TEXT NOT NULL, consumedAt TEXT);
CREATE TABLE IF NOT EXISTS assets (id TEXT PRIMARY KEY, filename TEXT NOT NULL, mime TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, kind TEXT NOT NULL, createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT NOT NULL, industry TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','paused','archived')), data TEXT NOT NULL, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS research (id TEXT PRIMARY KEY, projectId TEXT NOT NULL REFERENCES projects(id), sourceUrl TEXT, publishedAt TEXT, fetchedAt TEXT NOT NULL, provider TEXT NOT NULL, status TEXT NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs (id TEXT PRIMARY KEY, projectId TEXT NOT NULL REFERENCES projects(id), businessDate TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('scheduled','manual')), requestKey TEXT UNIQUE, status TEXT NOT NULL, createdAt TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS scheduled_daily ON runs(projectId,businessDate) WHERE kind='scheduled';
CREATE TABLE IF NOT EXISTS stories (id TEXT PRIMARY KEY, projectId TEXT NOT NULL REFERENCES projects(id), runId TEXT REFERENCES runs(id), slot INTEGER, businessDate TEXT NOT NULL, latestVersionId TEXT REFERENCES story_versions(id), createdAt TEXT NOT NULL, UNIQUE(runId,slot));
CREATE TABLE IF NOT EXISTS story_versions (id TEXT PRIMARY KEY, storyId TEXT NOT NULL REFERENCES stories(id), revision INTEGER NOT NULL, data TEXT NOT NULL, createdBy TEXT REFERENCES users(id), createdAt TEXT NOT NULL, UNIQUE(storyId,revision));
CREATE TRIGGER IF NOT EXISTS immutable_version_update BEFORE UPDATE ON story_versions BEGIN SELECT RAISE(ABORT,'Story versions are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_version_delete BEFORE DELETE ON story_versions BEGIN SELECT RAISE(ABORT,'Story versions are immutable'); END;
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, runId TEXT NOT NULL REFERENCES runs(id), slot INTEGER NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, availableAt TEXT NOT NULL, claimedAt TEXT, error TEXT, storyId TEXT REFERENCES stories(id), UNIQUE(runId,slot));
CREATE INDEX IF NOT EXISTS jobs_claim ON jobs(status,availableAt);
CREATE TABLE IF NOT EXISTS operations (id TEXT PRIMARY KEY, storyId TEXT NOT NULL REFERENCES stories(id), kind TEXT NOT NULL, status TEXT NOT NULL, error TEXT, createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS feedback (id TEXT PRIMARY KEY, storyId TEXT NOT NULL REFERENCES stories(id), versionId TEXT NOT NULL REFERENCES story_versions(id), userId TEXT NOT NULL REFERENCES users(id), target TEXT NOT NULL, text TEXT NOT NULL, applied INTEGER NOT NULL, createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approvals (id TEXT PRIMARY KEY, storyId TEXT NOT NULL REFERENCES stories(id), versionId TEXT NOT NULL UNIQUE REFERENCES story_versions(id), reviewerId TEXT NOT NULL REFERENCES users(id), createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS exports (id TEXT PRIMARY KEY, storyId TEXT NOT NULL REFERENCES stories(id), versionId TEXT NOT NULL REFERENCES story_versions(id), userId TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL, createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS migrations (name TEXT PRIMARY KEY, appliedAt TEXT NOT NULL);
